# Generated by Django 2.2.4 on 2019-08-10 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmallLedgerSite', '0002_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracost',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='extracosts', to='SmallLedgerSite.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
