# Generated by Django 2.2.4 on 2019-08-10 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SmallLedgerSite', '0003_auto_20190810_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='boughtDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
