# Generated by Django 2.2.4 on 2019-08-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmallLedgerSite', '0004_auto_20190810_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='boughtDate',
            new_name='boughtdate',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='soldDate',
            new_name='solddate',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='soldPrice',
            new_name='soldprice',
        ),
    ]
