# Generated by Django 2.2.4 on 2019-08-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmallLedgerSite', '0007_auto_20190813_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='solddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
