# Generated by Django 2.2.4 on 2019-08-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmallLedgerSite', '0009_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ownusage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
